server:
  port: 8080 #order服务端口
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

Feign:
  sentinel:
    enabled: true
  httpclient:
    enabled: true #支持httpclient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
  client:
    config:
      userClient:
        logger-level: basic
        read-timeout: 1000
#        connect-timeout: 1000





